export * from './About.tsx'
export * from './Home.tsx'
export * from './edu/faq.tsx'
export * from './edu/guides.tsx'
export * from './shops.tsx'
export * from './species/ligia.tsx'
export * from './species/Ligia/ligia-pallasii.tsx'
export * from './species/Armadillidium/klugii.tsx'